ci: update haskell-ci

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -1,6 +1,6 @@
 # This GitHub workflow config has been generated by a script via
 #
-#   haskell-ci 'github' 'cabal.project'
+#   haskell-ci 'github' '--haddock' '--hlint' '--hlint-job' '9.8.2' 'cabal.project'
 #
 # To regenerate the script (for example after adjusting tested-with) run
 #
@@ -8,9 +8,9 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.14.3
+# version: 0.18.1
 #
-# REGENDATA ("0.14.3",["github","cabal.project"])
+# REGENDATA ("0.18.1",["github","--haddock","--hlint","--hlint-job","9.8.2","cabal.project"])
 #
 name: Haskell-CI
 on:
@@ -19,7 +19,7 @@ on:
 jobs:
   linux:
     name: Haskell-CI - Linux - ${{ matrix.compiler }}
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-20.04
     timeout-minutes:
       60
     container:
@@ -33,37 +33,31 @@ jobs:
             compilerVersion: 9.12.3
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: true
           - compiler: ghc-9.10.2
             compilerKind: ghc
             compilerVersion: 9.10.2
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: false
           - compiler: ghc-9.8.4
             compilerKind: ghc
             compilerVersion: 9.8.4
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: false
           - compiler: ghc-9.6.7
             compilerKind: ghc
             compilerVersion: 9.6.7
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: false
           - compiler: ghc-9.4.8
             compilerKind: ghc
             compilerVersion: 9.4.8
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: false
           - compiler: ghc-9.2.8
             compilerKind: ghc
             compilerVersion: 9.2.8
             setup-method: ghcup
             allow-failure: false
-            keep-sdist: false
       fail-fast: false
     steps:
       - name: apt
@@ -71,10 +65,10 @@ jobs:
           apt-get update
           apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common libtinfo5
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.17.5/x86_64-linux-ghcup-0.1.17.5 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.20.0/x86_64-linux-ghcup-0.1.20.0 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
-          "$HOME/.ghcup/bin/ghcup" install ghc "$HCVER"
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.6.2.0
+          "$HOME/.ghcup/bin/ghcup" install ghc "$HCVER" || (cat "$HOME"/.ghcup/logs/*.* && false)
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.10.2.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
         env:
           HCKIND: ${{ matrix.compilerKind }}
           HCNAME: ${{ matrix.compiler }}
@@ -86,11 +80,13 @@ jobs:
           echo "CABAL_DIR=$HOME/.cabal" >> "$GITHUB_ENV"
           echo "CABAL_CONFIG=$HOME/.cabal/config" >> "$GITHUB_ENV"
           HCDIR=/opt/$HCKIND/$HCVER
-          HC=$HOME/.ghcup/bin/$HCKIND-$HCVER
+          HC=$("$HOME/.ghcup/bin/ghcup" whereis ghc "$HCVER")
+          HCPKG=$(echo "$HC" | sed 's#ghc$#ghc-pkg#')
+          HADDOCK=$(echo "$HC" | sed 's#ghc$#haddock#')
           echo "HC=$HC" >> "$GITHUB_ENV"
-          echo "HCPKG=$HOME/.ghcup/bin/$HCKIND-pkg-$HCVER" >> "$GITHUB_ENV"
-          echo "HADDOCK=$HOME/.ghcup/bin/haddock-$HCVER" >> "$GITHUB_ENV"
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.6.2.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          echo "HCPKG=$HCPKG" >> "$GITHUB_ENV"
+          echo "HADDOCK=$HADDOCK" >> "$GITHUB_ENV"
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.10.2.0 -vnormal+nowrap" >> "$GITHUB_ENV"
           HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
           echo "HCNUMVER=$HCNUMVER" >> "$GITHUB_ENV"
           echo "ARG_TESTS=--enable-tests" >> "$GITHUB_ENV"
@@ -137,25 +133,42 @@ jobs:
       - name: update cabal index
         run: |
           $CABAL v2-update -v
+      - name: cache (tools)
+        uses: actions/cache/restore@v3
+        with:
+          key: ${{ runner.os }}-${{ matrix.compiler }}-tools-c81e5f3f
+          path: ~/.haskell-ci-tools
       - name: install cabal-plan
         run: |
           mkdir -p $HOME/.cabal/bin
-          curl -sL https://github.com/haskell-hvr/cabal-plan/releases/download/v0.6.2.0/cabal-plan-0.6.2.0-x86_64-linux.xz > cabal-plan.xz
-          echo 'de73600b1836d3f55e32d80385acc055fd97f60eaa0ab68a755302685f5d81bc  cabal-plan.xz' | sha256sum -c -
+          curl -sL https://github.com/haskell-hvr/cabal-plan/releases/download/v0.7.3.0/cabal-plan-0.7.3.0-x86_64-linux.xz > cabal-plan.xz
+          echo 'f62ccb2971567a5f638f2005ad3173dba14693a45154c1508645c52289714cb2  cabal-plan.xz' | sha256sum -c -
           xz -d < cabal-plan.xz > $HOME/.cabal/bin/cabal-plan
           rm -f cabal-plan.xz
           chmod a+x $HOME/.cabal/bin/cabal-plan
           cabal-plan --version
+      - name: install hlint
+        run: |
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then HLINTVER=$(cd /tmp && (${CABAL} v2-install -v $ARG_COMPILER --dry-run hlint  --constraint='hlint >=3.5 && <3.6' |  perl -ne 'if (/\bhlint-(\d+(\.\d+)*)\b/) { print "$1"; last; }')); echo "HLint version $HLINTVER" ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then if [ ! -e $HOME/.haskell-ci-tools/hlint-$HLINTVER/hlint ]; then echo "Downloading HLint version $HLINTVER"; mkdir -p $HOME/.haskell-ci-tools; curl --write-out 'Status Code: %{http_code} Redirects: %{num_redirects} Total time: %{time_total} Total Dsize: %{size_download}\n' --silent --location --output $HOME/.haskell-ci-tools/hlint-$HLINTVER.tar.gz "https://github.com/ndmitchell/hlint/releases/download/v$HLINTVER/hlint-$HLINTVER-x86_64-linux.tar.gz"; tar -xzv -f $HOME/.haskell-ci-tools/hlint-$HLINTVER.tar.gz -C $HOME/.haskell-ci-tools; fi ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then mkdir -p $CABAL_DIR/bin && ln -sf "$HOME/.haskell-ci-tools/hlint-$HLINTVER/hlint" $CABAL_DIR/bin/hlint ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then hlint --version ; fi
+      - name: save cache (tools)
+        uses: actions/cache/save@v3
+        if: always()
+        with:
+          key: ${{ runner.os }}-${{ matrix.compiler }}-tools-c81e5f3f
+          path: ~/.haskell-ci-tools
       - name: checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v3
         with:
           path: source
       - name: initial cabal.project for sdist
         run: |
           touch cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/nonempty-wrapper-quickcheck" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/nonempty-wrapper-aeson" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/nonempty-wrapper-text" >> cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/nonempty-wrapper-quickcheck" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/nonempty-wrapper" >> cabal.project
           cat cabal.project
       - name: sdist
@@ -168,26 +181,26 @@ jobs:
           find sdist -maxdepth 1 -type f -name '*.tar.gz' -exec tar -C $GITHUB_WORKSPACE/unpacked -xzvf {} \;
       - name: generate cabal.project
         run: |
+          PKGDIR_nonempty_wrapper_quickcheck="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/nonempty-wrapper-quickcheck-[0-9.]*')"
+          echo "PKGDIR_nonempty_wrapper_quickcheck=${PKGDIR_nonempty_wrapper_quickcheck}" >> "$GITHUB_ENV"
           PKGDIR_nonempty_wrapper_aeson="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/nonempty-wrapper-aeson-[0-9.]*')"
           echo "PKGDIR_nonempty_wrapper_aeson=${PKGDIR_nonempty_wrapper_aeson}" >> "$GITHUB_ENV"
           PKGDIR_nonempty_wrapper_text="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/nonempty-wrapper-text-[0-9.]*')"
           echo "PKGDIR_nonempty_wrapper_text=${PKGDIR_nonempty_wrapper_text}" >> "$GITHUB_ENV"
-          PKGDIR_nonempty_wrapper_quickcheck="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/nonempty-wrapper-quickcheck-[0-9.]*')"
-          echo "PKGDIR_nonempty_wrapper_quickcheck=${PKGDIR_nonempty_wrapper_quickcheck}" >> "$GITHUB_ENV"
           PKGDIR_nonempty_wrapper="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/nonempty-wrapper-[0-9.]*')"
           echo "PKGDIR_nonempty_wrapper=${PKGDIR_nonempty_wrapper}" >> "$GITHUB_ENV"
           rm -f cabal.project cabal.project.local
           touch cabal.project
           touch cabal.project.local
+          echo "packages: ${PKGDIR_nonempty_wrapper_quickcheck}" >> cabal.project
           echo "packages: ${PKGDIR_nonempty_wrapper_aeson}" >> cabal.project
           echo "packages: ${PKGDIR_nonempty_wrapper_text}" >> cabal.project
-          echo "packages: ${PKGDIR_nonempty_wrapper_quickcheck}" >> cabal.project
           echo "packages: ${PKGDIR_nonempty_wrapper}" >> cabal.project
+          echo "package nonempty-wrapper-quickcheck" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package nonempty-wrapper-aeson" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package nonempty-wrapper-text" >> cabal.project
-          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
-          echo "package nonempty-wrapper-quickcheck" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package nonempty-wrapper" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
@@ -200,8 +213,8 @@ jobs:
         run: |
           $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dry-run all
           cabal-plan
-      - name: cache
-        uses: actions/cache@v4
+      - name: restore cache
+        uses: actions/cache/restore@v3
         with:
           key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
           path: ~/.cabal/store
@@ -210,7 +223,6 @@ jobs:
         run: |
           $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks --dependencies-only -j2 all
           $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dependencies-only -j2 all
-          $CABAL install $ARG_COMPILER hspec-discover
       - name: build w/o tests
         run: |
           $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks all
@@ -220,26 +232,32 @@ jobs:
       - name: tests
         run: |
           $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct
+      - name: hlint
+        run: |
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then (cd ${PKGDIR_nonempty_wrapper_quickcheck} && hlint -XHaskell2010 -XDataKinds -XDefaultSignatures -XDeriveAnyClass -XDeriveGeneric -XDerivingStrategies -XDerivingVia -XDuplicateRecordFields -XFlexibleContexts -XGADTs -XGeneralizedNewtypeDeriving -XKindSignatures -XLambdaCase -XOverloadedLists -XOverloadedStrings -XRankNTypes -XRecordWildCards -XScopedTypeVariables -XTypeApplications -XTypeFamilies -XTypeOperators src) ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then (cd ${PKGDIR_nonempty_wrapper_aeson} && hlint -XHaskell2010 -XDataKinds -XDefaultSignatures -XDeriveAnyClass -XDeriveGeneric -XDerivingStrategies -XDerivingVia -XDuplicateRecordFields -XFlexibleContexts -XGADTs -XGeneralizedNewtypeDeriving -XKindSignatures -XLambdaCase -XOverloadedLists -XOverloadedStrings -XRankNTypes -XRecordWildCards -XScopedTypeVariables -XTypeApplications -XTypeFamilies -XTypeOperators src) ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then (cd ${PKGDIR_nonempty_wrapper_text} && hlint -XHaskell2010 -XDataKinds -XDefaultSignatures -XDeriveAnyClass -XDeriveGeneric -XDerivingStrategies -XDerivingVia -XDuplicateRecordFields -XFlexibleContexts -XGADTs -XGeneralizedNewtypeDeriving -XKindSignatures -XLambdaCase -XOverloadedLists -XOverloadedStrings -XRankNTypes -XRecordWildCards -XScopedTypeVariables -XTypeApplications -XTypeFamilies -XTypeOperators src) ; fi
+          if [ $((HCNUMVER >= 90800)) -ne 0 ] ; then (cd ${PKGDIR_nonempty_wrapper} && hlint -XHaskell2010 -XDataKinds -XDefaultSignatures -XDeriveAnyClass -XDeriveGeneric -XDerivingStrategies -XDerivingVia -XDuplicateRecordFields -XFlexibleContexts -XGADTs -XGeneralizedNewtypeDeriving -XKindSignatures -XLambdaCase -XOverloadedLists -XOverloadedStrings -XRankNTypes -XRecordWildCards -XScopedTypeVariables -XTypeApplications -XTypeFamilies -XTypeOperators src) ; fi
       - name: cabal check
         run: |
+          cd ${PKGDIR_nonempty_wrapper_quickcheck} || false
+          ${CABAL} -vnormal check
           cd ${PKGDIR_nonempty_wrapper_aeson} || false
           ${CABAL} -vnormal check
           cd ${PKGDIR_nonempty_wrapper_text} || false
-          ${CABAL} -vnormal check
-          cd ${PKGDIR_nonempty_wrapper_quickcheck} || false
           ${CABAL} -vnormal check
           cd ${PKGDIR_nonempty_wrapper} || false
           ${CABAL} -vnormal check
       - name: haddock
         run: |
-          $CABAL v2-haddock $ARG_COMPILER --with-haddock $HADDOCK $ARG_TESTS $ARG_BENCH all
+          $CABAL v2-haddock --disable-documentation --haddock-all $ARG_COMPILER --with-haddock $HADDOCK $ARG_TESTS $ARG_BENCH all
       - name: unconstrained build
         run: |
           rm -f cabal.project.local
           $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks all
-      - uses: actions/upload-artifact@v4
-        if: ${{ matrix.keep-sdist }}
+      - name: save cache
+        uses: actions/cache/save@v3
+        if: always()
         with:
-          name: sdists
-          path: ${{ github.workspace }}/sdist/*.tar.gz
-          retention-days: 1
+          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ github.sha }}
+          path: ~/.cabal/store
